workflows:
  build_blackchain_app:
    name: Build Blackchain Crypto App
    instance_type: mac_mini_m1
    environment:
      vars:
        NODE_ENV: production
      node: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install --save-dev @vitejs/plugin-react
      - name: Build the app
        script: |
          npm run build
    artifacts:
      - dist/**
    publishing:
      email:
        recipients:
          - Kpphmri@gmail.com
        notify:
          success: true
          failure: true
