workflows:
  build_blackchain_app:
    name: Build Blackchain Crypto App
    instance_type: mac_mini_m1
    environment:
      node: latest
    scripts:
      - name: Clean install dependencies
        script: |
          rm -rf node_modules package-lock.json
          npm install
      - name: Build app
        script: |
          npm run build
    artifacts:
      - dist/**
    publishing:
      email:
        recipients:
          - Kpphmril.com
        notify:
          success: true
          failure: true
