workflows:
  build_blackchain_app:
    name: Build Blackchain Crypto App
    instance_type: mac_mini_m1
    environment:
      vars:
        NODE_ENV: production
      node: latest
    scripts:
      - name: Clean install dependencies
        script: |
          rm -rf node_modules package-lock.json
          npm install
      - name: Ensure plugin-react is present
        script: |
          npm install --save-dev @vitejs/plugin-react
      - name: Build the app
        script: |
          npm run build
          scripts:
  - name: Clean install dependencies
    script: |
      rm -rf node_modules package-lock.json
      npm install
    artifacts:
      - dist/**
    publishing:
      email:
        recipients:
          - Kpphmri@gmail.com
        notify:
          success: true
          failure: true
