workflows:
  build_blackchain_app:
    name: Build Blackchain Crypto App
    instance_type: mac_mini_m1
    environment:
      vars:
        NODE_ENV: production
      node: latest
    scripts:
      - name: Reset dependencies & force install everything
        script: |
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps
          npm install --save-dev @vitejs/plugin-react autoprefixer postcss
      - name: Verify installed dev dependencies
        script: |
          ls node_modules/@vitejs/plugin-react
          ls node_modules/autoprefixer
          ls node_modules/postcss
      - name: Build the app
        script: |
          npm run build
    artifacts:
      - dist/**
    publishing:
      email:
        recipients:
          - Kpphmri@gmail.com
        notify:
          success: true
          failure: true
