workflows:
  build_blackchain_app:
    name: Build Blackchain Crypto App
    instance_type: mac_mini_m1
    environment:
      vars:
        NODE_ENV: production
      node: latest
    scripts:
      - name: Clean & install exact dependencies
        script: |
          rm -rf node_modules
          npm ci
      - name: Build the app
        script: |
          npm run build
    artifacts:
      - dist/**
    publishing:
      email:
        recipients:
          - Kpphmri@gmail.com
        notify:
          success: true
          failure: true
